"""initial migration

Revision ID: e33d596163bc
Revises: 
Create Date: 2023-10-11 16:30:55.344369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33d596163bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_image', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('user_phone_number', sa.String(), nullable=True),
    sa.Column('user_address', sa.String(), nullable=True),
    sa.Column('user_city', sa.String(), nullable=True),
    sa.Column('user_state', sa.String(), nullable=True),
    sa.Column('user_zip_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breeder_id', sa.Integer(), nullable=True),
    sa.Column('dog_name', sa.String(), nullable=True),
    sa.Column('dog_image', sa.String(), nullable=True),
    sa.Column('dog_breed', sa.String(), nullable=True),
    sa.Column('dog_age', sa.String(), nullable=True),
    sa.Column('dog_gender', sa.String(), nullable=True),
    sa.Column('dog_weight', sa.String(), nullable=True),
    sa.Column('dog_color', sa.String(), nullable=True),
    sa.Column('dog_price', sa.Integer(), nullable=True),
    sa.Column('dog_description', sa.String(), nullable=True),
    sa.Column('up_for_adoption', sa.Boolean(), nullable=True),
    sa.Column('mother_name', sa.String(), nullable=True),
    sa.Column('mother_breed', sa.String(), nullable=True),
    sa.Column('mother_weight', sa.String(), nullable=True),
    sa.Column('mother_age', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('father_breed', sa.String(), nullable=True),
    sa.Column('father_weight', sa.String(), nullable=True),
    sa.Column('father_age', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['breeder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_sender_id', sa.Integer(), nullable=True),
    sa.Column('message_receiver_id', sa.Integer(), nullable=True),
    sa.Column('message_body', sa.String(), nullable=True),
    sa.Column('dog_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['message_receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('favorites')
    op.drop_table('dogs')
    op.drop_table('users')
    # ### end Alembic commands ###
